resourcestring

    // Error messages
    PermissonDenied = '%s: permission denied';
    StatFailed = 'failed to stat %s: %s';
    OpenDirFailed = 'failed to open directory %s: %s';

    // Command line flags
    ListDes = 'Show the output as a list';
    AllDes = 'Show everything, even hidden entries';
    ColorDes = 'Colorize the output';
    DirOnlyDes = 'Only show directories';
    IgnoreDes = 'Use regular expression to skip entities';
    IgnoreBckDes = 'Ignore entities whose name end with ~ or .bak';
    RecursiveDes = 'List stuff, recursively';
    WinFmtDes = 'List entities, Windows''s dir style';
    GNUFmtDes = 'List entities, GNU''s ls style';
    CCFmtDes = 'List entities, Commands-Collection''s style';