commit-message: 'i18n: Updates for %language% from Crowdin'
project_id: 891754
append_commit_message: 
preserver_hierarchy: true
files:
  - source: /i18n/dir.pot
    translation: /i18n/%two_letters_code%/dir.po
  - source: /i18n/env.pot
    translation: /i18n/%two_letters_code%/env.po
  - source: /i18n/hello.pot
    translation: /i18n/%two_letters_code%/hello.po
  - source: /i18n/inp.pot
    translation: /i18n/%two_letters_code%/inp.po
  - source: /i18n/rm.pot
    translation: /i18n/%two_letters_code%/rm.po
  - source: /i18n/touch.pot
    translation: /i18n/%two_letters_code%/touch.po
  - source: /i18n/uname.pot
    translation: /i18n/%two_letters_code%/uname.po
