resourcestring
    IGNORE_DES           = 'Ignore entities whose name match the -x pattern';
    DRY_RUN_DES          = 'Do not actually remove stuff';
    FILTER_DES           = 'Filter out stuff to delete / keep using regular expressions';
    RECURSIVE_DES        = 'Remove recursively';
    KEEP_GOING_DES       = 'Ignore errors';
    PROGRAM_DESC         = 'Removes files and directories';

    ATTEMPTING_TO_DELETE = 'Attempting to delete %s...';
    DELETE_CONFIRMATION  = 'Do you really want to remove %s? [yYnNaA] ';
    NOTHING_TO_DELETE    = 'Nothing to sacrifice.';
    FAILED_TO_DELETE     = 'Failed to delete %s: %s';
    DELETED              = 'Deleted %s.';
    NON_EXISTANT         = '%s does not exist';
    FILTERED             = 'Filtered out %s.';
