resourcestring
    MSG_DES = 'Custom message to show instead of Press any key/Enter to continue';
    LOOP_DES = 'Do not quit until a valid input is sent';
    HIDEOKOJIMA_DES = 'Hide inputs from the user';
    REQCHAR_DES = 'Specify valid characters';
    // CASESENS_DES = 'Make the input case-sensitive';

    PROGRAM_DESC = 'Asks for user input.';
    PROGRAM_BONUS_HELP =
        'If no arguments are provided, the program will simply ask for a key press, quits with exit code 0.' + CRNL +
        'Otherwise will quit with the exit code set to the ASCII value of the input character.';

	PRESS_ANY_KEY = 'Press any key to continue...';
