const
	ARGA: array of TOption = (
		(Long: 'all';       		Kind: EOptKind.FLAG; Short: 'a'),
		(Long: 'formatted';			Kind: EOptKind.FLAG; Short: 'f'),
		(Long: 'kernel-name';     	Kind: EOptKind.FLAG; Short: 's'),
		(Long: 'kernel-release';    Kind: EOptKind.FLAG; Short: 'r'),
		(Long: 'kernel-version';	Kind: EOptKind.FLAG; Short: 'v'),
		(Long: 'machine';			Kind: EOptKind.FLAG; Short: 'm'),
		(Long: 'nodename';			Kind: EOptKind.FLAG; Short: 'n'),
		(Long: 'processor';			Kind: EOptKind.FLAG; Short: 'p'),
		(Long: 'operating-system';  Kind: EOptKind.FLAG; Short: 'o'),
		ARGA_SUFFIX
	);
