resourcestring
    RAW_DES = 'Display raw uptime information';
    SINCE_DES = 'Display uptime since a specific date and time';
    PRETTY_DES = 'Display uptime in a human-readable format';
    PROGRAM_DESC = 'Displays system uptime';
    PROGRAM_BONUS_HELP = 'If you want to use -p, use it before any other flags. ' +
                         'Else you will get mixed results.';

    CURRENT_TIME = 'The current time is:';
    UPTIME_COUNT = 'The system is up for';
    UPTIME_FULL = '%d day(s) %d hour(s) %d minute(s) %d second(s)';
    USER_COUNT = '%d users';
    LOAD_AVG = 'Load average:';
    SYSINF_FAIL = 'sysinfo() failed: %s';
