{$define HAS_BONUS_HELP}

resourcestring
    RAW_DES = 'Display raw uptime information';
    SINCE_DES = 'Display uptime since a specific date and time';
    PRETTY_DES = 'Display uptime in a human-readable format';
    PROGRAM_DESC = 'Displays system uptime';
    PROGRAM_BONUS_HELP = 'If you want to use -p, use it before any other flags. ' +
                         'Else you will get mixed results.';
