resourcestring
    GREETING_DES            = 'Use TEXT as the greeting message';
    TRADITIONAL_DES         = 'Use traditional greeting message';

    HELLO_WORLD             = 'Hello world!';
    HELLO_WORLD_TRADITIONAL = 'hello world!';

    PROGRAM_DESC            = 'Prints a friendly, customizable greeting.';
    PROGRAM_BONUS_HELP      = 'This is a sample program from Commands-Collection.';
