name: Makefile CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install compiler
      run: sudo apt update && sudo apt install fpc -y
      
    - name: build_all
      run: make build_all
      
    - name: clean
      run: make clean
