name: Nightly CI

on:
  push:
    paths:
      - "*/**.pp"
      - "*/**.inc"
      - "*/**.c"
      - "*/**.h"
      - ".github/workflows/nightly.yml"

  pull_request:
    branches:
      - "main"
    paths:
      - "*/**.pp"
      - "*/**.inc"
      - "*/**.c"
      - "*/**.h"
      - ".github/workflows/nightly.yml"

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v6

      - name: Install compiler
        uses: gcarreno/setup-lazarus@v3.4.1
        with:
          with-cache: true

      - name: Setup XMake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: '.xmake-cache'
          actions-cache-key: ${{ matrix.os }}
          build-cache: true # We don't need it, but just in case
          build-cache-path: 'build/.build_cache'

      - name: Build
        run: |
          xmake f -m debug
          xmake b -v
          echo "artifacts=$(find build -type f -executable)" >> $GITHUB_ENV

      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          path: ${{ env.artifacts }}
          if-no-files-found: error
          name: CC Nightly for ${{ matrix.os }}
          compression-level: 0
