name: New release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        type: string
        required: true
      prerelease:
        description: Prerelease
        type: boolean
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v6

      - name: Install compiler
        uses: gcarreno/setup-lazarus@v3.4.1
        with:
          with-cache: true

      - name: Setup XMake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: '.xmake-cache'
          actions-cache-key: ${{ matrix.os }}
          build-cache: true # We don't need it, but just in case
          build-cache-path: 'build/.build_cache'

      - name: Build
        run: |
          xmake f -m release
          xmake b -v
          echo "artifacts=$(find build -type f -executable)" >> $GITHUB_ENV

      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          path: ${{ env.artifacts }}
          if-no-files-found: error
          name: CC ${{ github.event.inputs.version }} for ${{ matrix.os }}
          compression-level: 0

  publish:
    runs-on: ubuntu-latest

    needs: build

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7

      - name: Publish
        uses: softprops/action-gh-release@v2.5.0
        with:
          tag_name: ${{ github.event.inputs.version }}
          prerelease: ${{ github.event.inputs.prerelease }}
          draft: true
          body_path: ${{ github.workspace }}/changelogs/${{ github.event.inputs.version }}.md
          files: "CC ${{ github.event.inputs.version }}*"
          name: v${{ github.event.inputs.version }}
